### ISSUE TITLE
The "void setPort(int port);" function is meaningless.

### ISSUE THREAD

**Issue by sekkwai** [dobokirisame/QtHttpRequests#1]
As title.

The "sendRequest" function will only use the "Request::address()" to get the URL.
If I set the port as 8080, the post request still using port 80.

**P.S.**
I only test the PostJsonRequest::sendRequest

**Comment by dobokirisame** [comment]
Hello, @sekkwai.
Thank you for your feedback.
I've updated project recently. So it would be great if you check it.

**Comment by sekkwai** [comment]
Hi, @dobokirisame 
Sorry for the late reply.
Checked. It works now.

**P.S.**
I Only checked the "PostJsonRequest"
